### ISSUE TITLE
what is the different of zend_class_entry in zend_value and zend_object

### ISSUE THREAD

**Issue by JihanZhuang** [laruence/php7-internal#38]
typedef union _zend_value {
    zend_object      *obj;
    zend_class_entry *ce;
} zend_value;

struct _zend_object {
    zend_class_entry *ce;
};

I want to know that the different of them and how to use them efficiently?

**Comment by laruence** [comment]
hmm,  they are totally different things

object->ce means the class_entry of the object. which is common used.

zvalue->value.ce is just a way how we interpret an value in zend_value, it's a union, and is only used in Z_CE(EG(This)),  because it's better than   (zend_class_entry*)Z_PTR(EG(This))

thanks
